# 应用名称
spring:
  application:
    name: moreDB
  dsmysql:
    jdbcUrl: jdbc:mysql://localhost:3306/javamysql?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    #jdbcUrl: jdbc:mysql://localhost:3306/javamysql?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=UTC
    username: root 
    password: 123456 
    driverClassName: com.mysql.cj.jdbc.Driver 
  dspost:
    jdbcUrl: jdbc:postgresql://localhost:5432/first
    username: postgres 
    password: 123456 
    driverClassName: org.postgresql.Driver

  
      

# 应用服务 WEB 访问端口
server:
  port: 8081



